### ISSUE TITLE
wasme deploy istio failing

### ISSUE THREAD

**Issue by arunneoz** [solo-io/wasme#100]
Hello ,

I tried following the instructions and everything went smooth until wasme deploy istio step, where iam getting Error EOF 

wasme version: wasme version 0.0.19
client version: 1.5.0-beta.5
control plane version: 1.5.0-beta.5
data plane version: 1.5.0-beta.5 (9 proxies)
gke version:1.15.11-gke.1

wasme deploy istio webassemblyhub.io/arunneo/add-dataheader:v0.1  --id=dfilter  --namespace bookinfo  --config 'ITAR' --verbose
INFO[0000] cache namespace already exists                cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
INFO[0000] cache configmap already exists                cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
INFO[0000] cache service account already exists          cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
INFO[0000] cache role updated                            cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
INFO[0000] cache rolebinding updated                     cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
INFO[0000] cache daemonset updated                       cache=wasme-cache.wasme image="quay.io/solo-io/wasme:0.0.19"
DEBU[0000] resolving                                     host=webassemblyhub.io
DEBU[0000] do request                                    host=webassemblyhub.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.3.0+unknown request.method=HEAD url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/v0.1"
DEBU[0000] fetch response received                       host=webassemblyhub.io response.header.content-length=165 response.header.content-type="application/json; charset=utf-8" response.header.date="Fri, 03 Apr 2020 13:28:25 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=envoy response.header.set-cookie="sid=f92680b0f2888275e8fb39e65b9b2f5e; Path=/; HttpOnly" response.header.set-cookie.1="_xsrf=dU5jeWJLc2xjSWdTbnVZaDBKbVlVY3c1OFRvVjZvWFg=|1585920505584047170|e61f890664d749f96da8ede396d29cbcfaca5989; Expires=Fri, 03 Apr 2020 14:28:25 UTC; Max-Age=3600; Path=/" response.header.www-authenticate="Bearer realm=\"https://webassemblyhub.io/service/token\",service=\"harbor-registry\",scope=\"repository:arunneo/add-dataheader:pull\"" response.header.x-envoy-upstream-service-time=7 response.status="401 Unauthorized" url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/v0.1"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://webassemblyhub.io/service/token\",service=\"harbor-registry\",scope=\"repository:arunneo/add-dataheader:pull\"" host=webassemblyhub.io
DEBU[0000] do request                                    host=webassemblyhub.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.3.0+unknown request.method=HEAD url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/v0.1"
DEBU[0001] fetch response received                       host=webassemblyhub.io response.header.content-length=893 response.header.content-security-policy="frame-ancestors 'none'" response.header.content-type=application/vnd.oci.image.manifest.v1+json response.header.date="Fri, 03 Apr 2020 13:28:25 GMT" response.header.docker-content-digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba\"" response.header.server=envoy response.header.set-cookie="sid=29404c660b1fd9c8879e4a82e3122c90; Path=/; HttpOnly" response.header.set-cookie.1="_xsrf=YlQzTkdQNFExcTNPNU9kU2tpTmJvRTN3OGZCc3o5dnA=|1585920505657043488|f154fb21b925cff80a1960dec2fffc505006304a; Expires=Fri, 03 Apr 2020 14:28:25 UTC; Max-Age=3600; Path=/" response.header.x-envoy-upstream-service-time=194 response.header.x-frame-options=DENY response.status="200 OK" url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/v0.1"
DEBU[0001] resolved                                      desc.digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" host=webassemblyhub.io
DEBU[0001] fetch                                         digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" mediatype=application/vnd.oci.image.manifest.v1+json size=893
DEBU[0001] do request                                    digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" mediatype=application/vnd.oci.image.manifest.v1+json request.header.accept="application/vnd.oci.image.manifest.v1+json, */*" request.header.user-agent=containerd/1.3.0+unknown request.method=GET size=893 url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba"
DEBU[0001] fetch response received                       digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" mediatype=application/vnd.oci.image.manifest.v1+json response.header.content-length=893 response.header.content-security-policy="frame-ancestors 'none'" response.header.content-type=application/vnd.oci.image.manifest.v1+json response.header.date="Fri, 03 Apr 2020 13:28:25 GMT" response.header.docker-content-digest="sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba\"" response.header.server=envoy response.header.set-cookie="sid=14ecb549f617c1c283690fd10685e692; Path=/; HttpOnly" response.header.set-cookie.1="_xsrf=bUgyVzI5UzdTVnJkdlhZTExpRFJ4Zm00ak44MldmWjM=|1585920505853363572|bdb3790199a49bfc0ceec4c8d84fe05067339aa5; Expires=Fri, 03 Apr 2020 14:28:25 UTC; Max-Age=3600; Path=/" response.header.x-envoy-upstream-service-time=195 response.header.x-frame-options=DENY response.status="200 OK" size=893 url="https://webassemblyhub.io/v2/arunneo/add-dataheader/manifests/sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba"
DEBU[0001] webassemblyhub.io/arunneo/add-dataheader:v0.1 [{MediaType:application/vnd.module.wasm.config.v1+json Digest:sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770 Size:166 URLs:[] Annotations:map[org.opencontainers.image.title:runtime-config.json] Platform:<nil>} {MediaType:application/vnd.module.wasm.config.v1+json Digest:sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770 Size:166 URLs:[] Annotations:map[org.opencontainers.image.title:runtime-config.json] Platform:<nil>} {MediaType:application/vnd.module.wasm.content.layer.v1+wasm Digest:sha256:6316aa51b3dc11854a1967a393b0535aabd4e119ec7d37c041c414f4d7277a42 Size:12615 URLs:[] Annotations:map[org.opencontainers.image.title:filter.wasm] Platform:<nil>}] {MediaType:application/vnd.oci.image.manifest.v1+json Digest:sha256:c5445718400e652db7f832d5abc7e4d88b0eaae83b76b0c5689e6bfe8edab7ba Size:893 URLs:[] Annotations:map[] Platform:<nil>} <nil>
DEBU[0001] do request                                    digest="sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770" request.header.accept="application/vnd.module.wasm.config.v1+json, */*" request.header.user-agent=containerd/1.3.0+unknown request.method=GET url="https://webassemblyhub.io/v2/arunneo/add-dataheader/blobs/sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770"
DEBU[0001] fetch response received                       digest="sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770" response.header.accept-ranges=bytes response.header.cache-control="max-age=31536000" response.header.content-length=0 response.header.content-security-policy="frame-ancestors 'none'" response.header.content-type=application/octet-stream response.header.date="Fri, 03 Apr 2020 13:28:25 GMT" response.header.docker-content-digest="sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770\"" response.header.server=envoy response.header.set-cookie="sid=21755e867c58513b777717b5f2afc217; Path=/; HttpOnly" response.header.set-cookie.1="_xsrf=bDJqMG9qZ0lTTzRIZE5PMmUwc285MXJ1OXNoVjd2ZHc=|1585920506051567156|5f22c9b613e6ee302f0c29910158e44c4edf0152; Expires=Fri, 03 Apr 2020 14:28:26 UTC; Max-Age=3600; Path=/" response.header.x-envoy-upstream-service-time=21 response.header.x-frame-options=DENY response.status="200 OK" url="https://webassemblyhub.io/v2/arunneo/add-dataheader/blobs/sha256:766ecd72b4cc55952c00650f1a77b5f138207e76b5b2a241352ef245203af770"
Error: EOF
Usage:
  wasme deploy istio <image> --id=<unique name> [--config=<inline string>] [--root-id=<root id>] [--namespaces <comma separated namespaces>] [

**Comment by yuval-k** [comment]
hi, we are looking into this

**Comment by yuval-k** [comment]
this error should be resolved. we are looking at to the root cause

**Comment by arunneoz** [comment]
@yuval-k  , let me know when its fixed. Thanks for looking into it

**Comment by arunneoz** [comment]
Thanks i tested it , seems to be working now.
