### ISSUE TITLE
wasme --cache running within k8s fails authentication against an OCI registry

### ISSUE THREAD

**Issue by vbergbauer** [solo-io/wasme#101]
Since wasme uses the OCI registry format, I wanted to test against gcr.io.
Almost everything works except wasme cache when running inside of Kubernetes.

# Environment

- Client: Ubuntu 16.04 on WSL1 (Windows build 1909). Everything works there.
- Kubernetes: 1.15.5 on Docker Desktop community 2.2.0.5 (engine version 19.03.8)

# Steps

## Set the credentials

```bash
# Set the project ID used by gcr
PROJECT_ID=$(gcloud config list --format='get(core.project)')

# Create service account and assign role for the bucket used by GCR.
SERVICE_ACCOUNT_NAME=gcr-client
SERVICE_ACCOUNT=$SERVICE_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com
SERVICE_ACCOUNT_FILE=$HOME/$PROJECT_ID-$SERVICE_ACCOUNT_NAME.json

gcloud --project=$PROJECT_ID iam service-accounts create $SERVICE_ACCOUNT_NAME
gsutil iam ch "serviceAccount:$SERVICE_ACCOUNT:admin" gs://artifacts.$PROJECT_ID.appspot.com
gcloud --project=$PROJECT_ID iam service-accounts keys create --iam-account=$SERVICE_ACCOUNT $SERVICE_ACCOUNT_FILE

# Set user and password variables
# See https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
GCR_USER=_json_key
GCR_PASSWORD="$(cat $SERVICE_ACCOUNT_FILE)"
```

## Use wasme successfully on the client

```bash
# Fetch a public image
IMAGE_NAME=ilackarms/assemblyscript-test
IMAGE_VERSION=istio-1.5
wasme pull webassemblyhub.io/$IMAGE_NAME:$IMAGE_VERSION

# Retag it
GCR_IMAGE=gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_VERSION
wasme tag webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5 $GCR_IMAGE

# Push image: SUCCESS
wasme push -u "$GCR_USER" -p "$GCR_PASSWORD" $GCR_IMAGE

# Clear the wasme store
rm -r ~/.wasme/store/*
wasme list

# Pull the image we have just pushed: SUCCESS
wasme pull -u "$GCR_USER" -p "$GCR_PASSWORD" $GCR_IMAGE

# Use wasme cache: SUCCESS
echo $GCR_IMAGE > images.txt
mkdir -p wasme-cache
wasme cache --ref-file images.txt --directory wasme-cache --cache-ns default \
  -u "$GCR_USER" -p "$GCR_PASSWORD" -v

```

## Use wasme in a pod

```bash
# Start interactive pod with environment variable
kubectl run wasme-tmp \
--image=quay.io/solo-io/wasme:0.0.19 \
--generator=run-pod/v1 --grace-period=1 -it --rm \
--overrides="$(jq -n '{metadata: {annotations: {"sidecar.istio.io/inject":"false"}}}')" \
--env "GCR_IMAGE=$GCR_IMAGE" \
--env "GCR_USER=$GCR_USER" \
--env "GCR_PASSWORD=$GCR_PASSWORD" \
--command -- /bin/sh

# Pull the image we have just pushed: SUCCESS
wasme pull -u "$GCR_USER" -p "$GCR_PASSWORD" $GCR_IMAGE
wasme list -d

# Use wasme cache: FAIL
echo $GCR_IMAGE > images.txt
mkdir wasme-cache
wasme cache --ref-file images.txt --directory wasme-cache --cache-ns default \
  -u "$GCR_USER" -p "$GCR_PASSWORD" -v
```

You can see that the error in the command is on the request to list manifests:

```
ERRO[0002] caching image failed: All attempts fail:
#1: unexpected status code [manifests istio-1.5]: 401 Unauthorized
```

In fact, you get the same error as when making a HEAD request without credentials:

```bash
apk add curl

# Request URL
URL=$(echo $GCR_IMAGE | sed -r 's#gcr\.io/(.+):(.+)#https://gcr.io/v2/\1/manifests/\2#')

curl --head "$URL"
```

Curl with valid credentials succeeds:

```bash
# HEAD
curl --head -u "$GCR_USER:$GCR_PASSWORD" "$URL"
# GET
curl -u "$GCR_USER:$GCR_PASSWORD" "$URL"
```

Are you missing some retry logic when in Kubernetes mode?

**Comment by yuval-k** [comment]
i think the issue is that we didnt expect this use case 

this is the line where the credentials should be used:
https://github.com/solo-io/wasme/blob/34a5e7385207a5897650fdb56f774041d386b981/pkg/defaults/defaults.go#L14

compare with pull:

https://github.com/solo-io/wasme/blob/34a5e7385207a5897650fdb56f774041d386b981/pkg/cmd/pull/pull.go#L45

essentially we need to plumb the user/password to the cache command as well.

I'll keep this open until this is resolved.

If you are up to create a PR for this, I can give you some pointers

**Comment by vbergbauer** [comment]
Thank you Yuval,
I am testing the necessary changes today. Expect a PR tomorrow...

Separately, we will have to look at a way to pick the [FilterDeployment pullSecret](https://github.com/solo-io/wasme/blob/master/operator/api/wasme/v1/filter_deployment.proto#L58) dynamically.

For the time being, I am just changing the wasme-cache daemonset locally to pick the GCR secret from a secret in the wasme namespace.

**Comment by yuval-k** [comment]
sounds great! thank you
