### ISSUE TITLE
wasme deploy envoy default Envoy image not compatible with Rust SDK

### ISSUE THREAD

**Issue by charypar** [solo-io/wasme#107]
Trying to run `wasme deploy envoy` with an image built with Rust and the [Rust SDK]() for proxy-wasm crashes with `WASM missing malloc/free`. 

The Rust SDK doesn't expose `free`, because it is no longer required (see https://github.com/envoyproxy/envoy-wasm/pull/404), but it looks like the default Envoy docker image used (`quay.io/solo-io/gloo-envoy-wasm-wrapper:1.3.5`) doesn't have this change.

Running with Istio 1.5 proxy works:
```
wasme deploy envoy <image-name> --envoy-image=istio/proxyv2:1.5.1
```

**Comment by yuval-k** [comment]
thank you! we will update. what filter image are you using to test? i want to make sure there are no other changes.

**Comment by charypar** [comment]
This one: https://webassemblyhub.io/repositories/150/rust_hello_world

The code is here, if you'd like to have a look: https://github.com/charypar/proxy-wasm-demo.
