### ISSUE TITLE
wasme pull images error

### ISSUE THREAD

**Issue by sunzhaochang** [solo-io/wasme#109]
Hi,

I have built and pushed the image, which can be found by `wasme list --search`. But "Error: EOF" occurred when I try to pull the image.

wasme version 0.0.20

The details are as follows:

$ wasme list --search sunboy0213
NAME                                    TAG  SIZE   SHA      UPDATED
webassemblyhub.io/sunboy0213/add-header v0.1 1.0 MB c993d8be 15 Apr 20 03:16 UTC
webassemblyhub.io/sunboy0213/add-header v0.2 1.0 MB c993d8be 15 Apr 20 04:54 UTC
$ wasme pull webassemblyhub.io/sunboy0213/add-header:v0.2
INFO[0000] Pulling image webassemblyhub.io/sunboy0213/add-header:v0.2
Error: EOF
Usage:
  wasme pull <name:tag|name@digest> [flags]

**Comment by yuval-k** [comment]
hello, this problem should be resolved; it seems to be related to docker-registry\redis; i think i'll just disable redis for now

**Comment by sunzhaochang** [comment]
> hello, this problem should be resolved; it seems to be related to docker-registry\redis; i think i'll just disable redis for now

Thanks for your reply, I just tried and it has worked correctly. 
Thank you very much.

**Comment by uhinze** [comment]
@yuval-k having this same problem with my own image now. What did you do to resolve the issue?
```
$ wasme pull webassemblyhub.io/uhinze/add-header:0.1
INFO[0000] Pulling image webassemblyhub.io/uhinze/add-header:0.1
Error: EOF
Usage:
  wasme pull <name:tag|name@digest> [flags]
...
```

**Comment by yuval-k** [comment]
hi @uhinze please try now; i'm chasing the root cause of this; something with the interaction of docker-registry and redis. though i can't seem to reproduce it in our staging environment. i have a potential solution in mind so these should go away soon.

**Comment by uhinze** [comment]
Worked now, @yuval-k , thanks! Suggest to keep this issue open til the underlying issue is fixed.
In any case, let me know when you’d like some retesting from me.

**Comment by tomersolomon1** [comment]
I'm having the same issue with the demo example from https://docs.solo.io/web-assembly-hub/latest/tutorial_code/wasme_operator/ (after updating the image to be webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5, as the previous image doesn't exist anymore)
```
tomersol@hrl-dc-bm:~$ cat <<EOF | kubectl apply -f -
apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: bookinfo-custom-filter
  namespace: bookinfo
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    config: '{"name":"hello","value":"world"}'
    image: webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5
EOF
filterdeployment.wasme.io/bookinfo-custom-filter created
tomersol@hrl-dc-bm:~$ kubectl get filterdeployments.wasme.io -n bookinfo -o yaml bookinfo-custom-filter
apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"wasme.io/v1","kind":"FilterDeployment","metadata":{"annotations":{},"name":"bookinfo-custom-filter","namespace":"bookinfo"},"spec":{"deployment":{"istio":{"kind":"Deployment"}},"filter":{"config":"{\"name\":\"hello\",\"value\":\"world\"}","image":"webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5"}}}
  creationTimestamp: "2020-05-24T13:20:37Z"
  generation: 1
  name: bookinfo-custom-filter
  namespace: bookinfo
  resourceVersion: "13826579"
  selfLink: /apis/wasme.io/v1/namespaces/bookinfo/filterdeployments/bookinfo-custom-filter
  uid: 6946eb78-80cc-4d56-9f92-4998c0c82349
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    config: '{"name":"hello","value":"world"}'
    image: webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5
status:
  observedGeneration: "1"
  reason: EOF
  workloads: {}
```

Also, I can't pull that image with the same error:
```
tomersol@hrl-dc-bm:~$ wasme pull webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5
INFO[0000] Pulling image webassemblyhub.io/ilackarms/assemblyscript-test:istio-1.5
Error: EOF
```

**Comment by oleksiyp** [comment]
For me, this is a show stopper. Probably for everybody it is as well a show stopper.

**Comment by yuval-k** [comment]
i have completely disabled redis; which should solve this issue. please re-open if this is still a problem!
