### ISSUE TITLE
build meet: ERROR: STANDALONE_WASM does not support pthreads yet

### ISSUE THREAD

**Issue by Masterlvng** [solo-io/wasme#118]
when building with com_google_protobuf, it show error below

/root/.cache/bazel/_bazel_root/2184e8aa3cf974e44c7c10c1e5ddc7a9/external/com_google_protobuf/BUILD:110:1: C++ compilation of rule '@com_google
_protobuf//:protobuf_lite' failed (Exit 1) emcc.sh failed: error executing command toolchain/emcc.sh -MD -MF bazel-out/wasm-fastbuild/bin/external/co
m_google_protobuf/_objs/protobuf_lite/generated_message_table_driven_lite.d ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
shared:ERROR: STANDALONE_WASM does not support pthreads yet

wasme: 0.0.20

git_repository(
    name = "com_google_protobuf",
    remote = "https://github.com/protocolbuffers/protobuf",
    commit = "655310ca192a6e3a050e0ca0b7084a2968072260",
)

**Comment by yuval-k** [comment]
this error is most likely related to the code you are trying to compile. is the source available publicly?
are you trying to compile a multi threaded program?
