### ISSUE TITLE
When wasme can support istio 1.6.1?

### ISSUE THREAD

**Issue by Hinsteny** [solo-io/wasme#125]
now i use wasme 0.0.2, it only can select istio 1.5.x, but not support 1.6.1.

**Comment by yuval-k** [comment]
i believe @Sodman was looking into to update wasme to support newer version of gloo/istio. envoy-wasm does change frequently, so i'm not sure if it will be compatbile with 1.6.1 or 1.6.2

**Comment by Hinsteny** [comment]
tks
